name: Update Meta IPs

on:
  schedule:
    - cron: '0 3 * * *'  # هر روز ساعت 3 صبح UTC (5:30 ایران)
  workflow_dispatch:      # اجرای دستی

permissions:
  contents: write

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Install jq
      run: sudo apt-get install -y jq

    - name: Fetch Meta IP prefixes
      run: |
        curl -s "https://api.bgpview.io/asn/32934/prefixes" \
        | jq -r '.data.ipv4_prefixes[],.data.ipv6_prefixes[] | .prefix' \
        > meta-ips.txt

    - name: Commit & Push changes
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git add meta-ips.txt
        git commit -m "Update Meta IP list automatically" || echo "No changes to commit"
        git push
