name: Update Meta IPs

on:
  schedule:
    - cron: '0 3 * * *'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Install jq
      run: sudo apt-get update && sudo apt-get install -y jq

    - name: Download JSON
      run: |
        wget -O ip-ranges.json https://developers.facebook.com/static/docs/graph-api/ip-ranges.json

    - name: Extract prefixes
      run: |
        cat ip-ranges.json | jq -r '.prefixes[] | select(.ip_prefix != null) | .ip_prefix' > meta-ips.txt

    - name: Commit & Push changes
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git add meta-ips.txt
        git commit -m "Update Meta IP list automatically" || echo "No changes to commit"
        git push
